# Generated by Django 3.2.7 on 2021-09-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['approved_comment', '-created_date']},
        ),
    ]
