# Generated by Django 3.2.7 on 2021-09-15 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date', 'created_date']},
        ),
    ]
